# Generated by Django 5.2.7 on 2026-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='company_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='employee_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
