# Generated by Django 5.2.7 on 2026-02-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_demorequest_company_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='employee_size',
            field=models.CharField(blank=True, null=True),
        ),
    ]
