# Generated by Django 5.2.7 on 2026-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_demorequest_employee_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_otp_required',
            field=models.BooleanField(default=True),
        ),
    ]
