# Generated by Django 5.2.7 on 2026-02-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0001_initial'),
        ('organizations', '0001_initial'),
        ('phone_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiphonecallconfig',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_number.twiliophonenumber'),
        ),
        migrations.AddField(
            model_name='aiphonecallconfig',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationplatform'),
        ),
        migrations.AddField(
            model_name='interviewcallconversation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='interviewtaken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='interviewcallconversation',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewtaken'),
        ),
        migrations.AddField(
            model_name='questionconfigconnection',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.aiphonecallconfig'),
        ),
        migrations.AddField(
            model_name='questionconfigconnection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.primaryquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='aiphonecallconfig',
            unique_together={('organization', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='questionconfigconnection',
            unique_together={('question', 'config')},
        ),
    ]
