# Generated by Django 5.2.7 on 2026-02-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtaken',
            name='from_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
